- .travis.yml
> Wip travis

- CMakeLists.txt
- src/c_peering.cpp
- src/test/Makefile
- src/test/xint.cpp
- src/test/xint_tmp.cpp
- src/xint.hpp
The safe int starts to be usable.
(though still could use even more UTs, esp. re unsigned variant and sign vs unsing)
> Style xint - basic safe int

- LICENCE-by-Antinet.txt
- LICENCE.txt
- README.md
Some clarification that the GPL can be changed away.
(Until we can put in a full nice legal document about contributing code,
explaining how it will remain open-source and patent-free always).
Also Yedino name - and the bitcoin key for signing.
Also small doc bugfixes etc.
@da2ce7 please tell me if this looks ok. I will rather merge PRs now (because I git GPG sign the merges too now)
> [doc] Licence: Yedino, bitcoin key, GPL relicense

- CMakeLists.txt
- build-extra-libs.sh
- do
- doc/hacking.md
- src/crypto/crypto.cpp
- src/crypto/crypto.hpp
- src/crypto/multikeys.cpp
- src/crypto/ntrupp.cpp
- src/crypto/ntrupp.hpp
- src/crypto/sidhpp.cpp
- src/crypto/sidhpp.hpp
- src/g42-main.cpp
- src/generate_crypto.cpp
- src/project.cpp
- src/project.hpp
- src/tunserver.cpp
- src/tunserver.hpp
- src/ui.cpp
- src/ui.hpp
Now with keygen fix (NTru - 0 signatures)
> Build extlevel - now with key gen fix #2

- .travis.yml
- CMakeLists.txt
- build-extra-libs.sh
- do
- doc/Doxyfile
- doc/hacking.md
- src/crypto/crypto.cpp
- src/crypto/crypto.hpp
- src/project.cpp
- src/project.hpp
extra:
+ some commits that updates CMakeLists.txt, "do" and "build-extra-libs.sh" scripts.
+ update doxygen
@rfree2 I did not notice that I rebased to your version before I started my work.
Maybe your commits disappear when you merge your changes first. It should be compatible.
> Generaly upgrade and fix builds in travis CI

- .travis.yml
- CMakeLists.txt
- doc/build-arch.md
- doc/build-osx.md
- src/c_peering.cpp
- src/crypto/crypto.hpp
- src/crypto/crypto_basic.hpp
- src/crypto/multikeys.hpp
- src/crypto/ntrupp.cpp
- src/crypto/ntrupp.hpp
- src/tunserver.cpp
- separate code that compiles only for linux with ifdef's (could be useful also for windows)
- brings build on osx to linking step, osx compilation can be been observed on travis ci.
- doc instructions for osx and arch.
- update submodule for libsidh
> [wip] Builds on osx,  switch to new libsidh + doc's

- src/datastore.cpp
canonical in mlocked save/load
> datastore win wstring compatibility

- src/g42-main.cpp
- src/haship.cpp
- src/haship.hpp
- src/test/haship.cpp
small fixes to keep our win32 work working well on linux too
> Wip win32 and linux fixes1

- src/c_ip46_addr.hpp
now we can connect from linux to windows
> default udp port on windows

- contrib/devtools/github-merge.py
https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/github-merge.py
10d3ae102afb89b3f50cd27f9ee657e5a542eb1b
All credit goes to the Bitcoin Core Developers.
> Add Bitcoin Github Merging Tool

- build-gitian
- works on systems without Xenial template
- works on systems with Xenial template
- allows OPTION to disable auto fixing of missing Xenial, so will NOT work on systems without xenial. read help to see that option
> [fix] debootstrap no need to fix

- .travis.yml
Maybe parentheses and quotes will help?
> .travis apt-source change format, ppa:ubuntu-toolchain-r/test problem

- do
- install.sh
- share/script/setup-ubuntu14-host
[add] ppa for libsodium and g++ to automatic build dependencies on ubuntu
> install.sh do - support ubuntu trusty and precise

- build-gitian
- contrib/gitian-descriptors/main-build/galaxy-windows-script
- contrib/gitian-descriptors/main-build/galaxy-windows-script-master
- do
- install.sh
Successful gitian build process on ubuntu and debian.
But still non deterministic galaxy42_installer.exe.
> More gitian fixes.

- build-gitian
- contrib/gitian-descriptors/main-build/galaxy-windows-script
- contrib/nsis-installer-windows/galaxy-windows-installer
- doc/build-gitian.md
+ FAQ gitian
+ zlib actually deterministic
- still trying to make nsis build deterministic
> some fixes - wip make installer deterministic

- contrib/nsis-installer-windows/galaxy-windows-installer
- contrib/nsis-installer-windows/installer.nsi
> Fix path to windows installer bin dir

- .travis.yml
- do
- doc/build-gitian.md
- share/script/setup-osx-brew
- src/c_event_manager.cpp
- src/c_event_manager.hpp
- src/c_ip46_addr.cpp
- src/c_ip46_addr.hpp
- src/c_peering.cpp
- src/c_peering.hpp
- src/c_tun_device.cpp
- src/c_tun_device.hpp
- src/c_udp_wrapper.cpp
- src/c_udp_wrapper.hpp
- src/datastore.cpp
- src/g42-main.cpp
- src/tunserver.cpp
- src/tunserver.hpp
- fix travis, integration for osx
- refactor ifdef's, include __MACH__
- datastore for mach fix
- new  c_event_manager_mach
- comment typo's in g42-main.cpp
> tunserver compilation on apple osx

- CMakeLists.txt
- contrib/gitian-descriptors/libboost-build/build-boost-osx
- contrib/gitian-descriptors/libboost-build/build-boost-static
- contrib/gitian-descriptors/main-build/galaxy-windows-script
add "libs/circular_buffer" submodule for boost build.
> Fix gitian builder and coverage tests.

- src-gui/addressdialog.cpp
- src-gui/addressdialog.hpp
- src-gui/addressdialog.ui
- src-gui/commandexecutor.cpp
- src-gui/commandexecutor.hpp
- src-gui/commandparser.cpp
- src-gui/commandparser.hpp
- src-gui/dataeater.cpp
- src-gui/dataeater.hpp
- src-gui/debugdialog.cpp
- src-gui/debugdialog.hpp
- src-gui/debugdialog.ui
- src-gui/get_host_info.cpp
- src-gui/get_host_info.hpp
- src-gui/get_host_info.ui
- src-gui/main.cpp
- src-gui/mainwindow.cpp
- src-gui/mainwindow.hpp
- src-gui/mainwindow.ui
- src-gui/netclient.cpp
- src-gui/netclient.hpp
- src-gui/paramscontainer.cpp
- src-gui/paramscontainer.hpp
- src-gui/qtest/main.cpp
- src-gui/qtest/t_dataeater.hpp
- src-gui/simpleGui.pro
- src-gui/trivialserialize.cpp
- src-gui/trivialserialize.hpp
- src-gui/tunserver_process.cpp
- src-gui/tunserver_process.hpp
full-history could be checked in: https://github.com/damianbb/simple_gui
> [add] source of simple_gui for tunserver

- contrib/macdeploy/build-dmg.sh
[add]  contrib/macdeploy/build-dmg.sh
> [osx] build-dmg.sh script that build Galaxy42.pkg and put it into Galaxy42.dmg

- .gitmodules
- CMakeLists.txt
- contrib/gitian-descriptors/libboost-build/build-boost-static
- depends/cjdns-code/NetPlatform_darwin.c
- depends/cjdns-code/NetPlatform_linux.c
- depends/cjdns-code/syserr.h
- src-misc/locale/galaxy42_main/en.po
- src-misc/locale/galaxy42_main/messages.pot
- src-misc/locale/galaxy42_main/pl.po
- src/c_tun_device.cpp
- src/c_tun_device.hpp
- src/g42-main.cpp
- src/tunserver.cpp
Checking for tun/tap errors, enum for error codes
> Tuntap fixes

- contrib/gitian-descriptors/libboost-build/build-boost-osx
- contrib/gitian-descriptors/libboost-build/build-boost-static
- contrib/gitian-descriptors/libboost-build/dl-boost-submodules
- contrib/gitian-descriptors/main-build/galaxy-windows-script
* remove some code duplications
> Gitian - boost and boost submodules download improvement.

- README.md
- doc/support-testcase.txt
- src/g42-main.cpp
> Installer doc 

- CMakeLists.txt
- src/rpc/rpc.cpp
> Fix static linking to pthread

- doc/cygwin-instructions.md
- doc/translation-instructions-cygwin.txt
> translations on cygwin instructions

- contrib/gitian-descriptors/main-build/galaxy-windows-script-master
- generate all .mo files in galaxy-windows-script-master script
> [win][gitian] galaxy42-lang-update-all

- contrib/gitian-descriptors/main-build/galaxy-linux-script
- contrib/gitian-descriptors/main-build/galaxy-osx-script
- contrib/gitian-descriptors/main-build/galaxy-windows-script-master
- contrib/nsis-installer-windows/bin/README.txt
- contrib/nsis-installer-windows/bin/generate_nsis_filelist.sh
- contrib/nsis-installer-windows/galaxy-windows-installer
- contrib/nsis-installer-windows/installer.nsi
- Applying fix for /dev/fd for all gitian builds
- generate_nsis_filelist.sh script that autocratically generate file list for nsis installator.
> /dev/fd fix for win and osx and  generate_nsis_filelist.sh script.

- src/mo_reader.cpp
Fix segfault in language detection if env LANG is not set
> MAC segfault

- src/c_tun_device.cpp
- src/httpdbg/httpdbg-server.cpp
- src/tunserver.cpp
Removed not needed sleep before tun device reset
> Fix segmentation fault on windows after sleep

- Jenkinsfile
- contrib/gitian-descriptors/libboost-build/dl-boost-submodules
- doc/hacking.md
* doc
* reduce max-procs for boost submodules download from 4 to 2
> share Jenkinsfile for our CI test system

- contrib/gitian-descriptors/main-build/galaxy-osx-script
> Fix build-gitian -M

- Jenkinsfile
> [jenkins] GitHubPushTrigger for pipeline

- contrib/gitian-descriptors/galaxy-osx_pack-to-dmg.sh
- contrib/gitian-descriptors/main-build/galaxy-osx-script
- share/script/lib/create_faketime_wrappers.sh
* extract faketime_wrappers functions [refactoring]
> Update gitian for maxosx -- creating .dmg image

- contrib/gitian-descriptors/galaxy-osx_pack-to-dmg.sh
- contrib/macdeploy/build-xar.sh
- share/script/lib/create_faketime_wrappers.sh
- change xar repository to out fork with patch that read file_list.txt
- replace git describe by simple string "alpha-version"   # should be updated
- sha256sum Tunserver.dmg: 7357b33d7545d64b1512ce4dbaa2aa2844b5786742cf3eccc08ca095b098b6e7
> Gitian for macosx - Create deterministic .dmg installer.

- doc/Doxyfile
- src/g42-main.cpp
- src/newloop.cpp
- src/newloop.hpp
- src/test/trivialserialize.cpp
- src/utils/check.hpp
- src/utils/misc.hpp
* Document check.hpp as a example of some doxygen syntax.
*  Doxygen - add option to generate also compact latex document
> Doxygen update

- src-misc/locale/galaxy42_main/en.po
- src-misc/locale/galaxy42_main/ru.po
- src-misc/locale/galaxy42_main/uk.po
Completed translation from EN to UA and RU for files in folder "galaxy42_main".
> Complete translation to RU and UA for galaxy42_main

- menu
> Fix Ukrainian language displaying

- src/datastore.cpp
- src/datastore.hpp
- src/test/crypto.cpp
- src/test/datastore.cpp
- src/test/the_program_newloop.cpp
- src/text_ui.cpp
- src/the_program_newloop.cpp
* Replace catch(...), by specific errors.
> unit test for peer reference options, datastore update

- src/utils/misc.hpp
> fix cygwin build

- CMakeLists.txt
- contrib/gitian-descriptors/galaxy-osx_pack-to-dmg.sh
- contrib/gitian-descriptors/libboost-build/dl-boost-submodules
- contrib/gitian-descriptors/main-build/galaxy-linux-script
- contrib/gitian-descriptors/main-build/galaxy-osx-script
- contrib/gitian-descriptors/main-build/galaxy-windows-script
- contrib/tools/build-pack-linux.sh
- share/script/lib/create_faketime_wrappers.sh
- src/c_tun_device.cpp
- src/galaxysrv.hpp
- src/the_program_newloop.cpp
- src/tuntap/macosx/c_tuntap_macosx_obj.cpp
- src/tuntap/macosx/c_tuntap_macosx_obj.hpp
* empty class:  c_tuntap_macosx_obj
* windows version not tested.
* some refactoring / cleaning code.
> [update] gitian builds

- doc/cmdline/newloop-comp107/galaxy42.cmdline
- doc/hacking.md
- src/cable/asio_ioservice_manager.cpp
- src/cable/asio_ioservice_manager.hpp
- src/cable/asiocable.hpp
- src/cable/base/cable_base_addr.cpp
- src/cable/base/cable_base_addr.hpp
- src/cable/base/cable_base_obj.cpp
- src/cable/base/cable_base_obj.hpp
- src/cable/cards.cpp
- src/cable/cards.hpp
- src/cable/kind.hpp
- src/cable/shm/cable_shm_obj.cpp
- src/cable/shm/cable_shm_obj.hpp
- src/cable/simulation/cable_simul_obj.cpp
- src/cable/simulation/cable_simul_obj.hpp
- src/cable/udp/cable_udp_obj.cpp
- src/cable/udp/cable_udp_obj.hpp
- src/galaxysrv.cpp
- src/galaxysrv.hpp
- src/galaxysrv_peers.hpp
- src/test/cable_test.cpp
> fix ioservice thread

- doc/Doxyfile
- doc/class_owners.md
- doc/hacking.md
- src/c_tun_device.hpp
- src/galaxysrv.hpp
> Doxygen - add \owner and \thread custom commands

- contrib/ci/autotest/set1/run.sh
+ Change path to tunserver.elf
> [ci] Fix integration tests,

- doc/build-gitian.md
> Fix Typo #325

- CMakeLists.txt
- doc/hacking.md
- src/libs0.cpp
- src/libs0.hpp
- src/stdplus/misc.cpp
- src/stdplus/misc.hpp
- src/stdplus/tab.cpp
- src/stdplus/tab.hpp
- src/test/Makefile
- src/test/stdplus_tab.cpp
stdplus::copy_safe_apart
and with unittests
> J468 copy safe apart

- doc/Doxyfile
- doc/hacking.md
- src/crypto/crypto.cpp
- src/crypto/crypto_basic.hpp
- src/crypto/multikeys.cpp
- src/libs0.hpp
- src/platform.hpp
- src/rpc/rpc.cpp
- src/stdplus/misc.hpp
- src/stdplus/tab.hpp
- src/strings_utils.hpp
- src/strings_utils_base.hpp
- src/test/Makefile
- src/test/_templ.cpp
- src/test/my_tests_lib.cpp
- src/test/stdplus_misc.cpp
- src/test/stdplus_tab.cpp
- src/test/the_program_newloop.cpp
- src/test/utility.cpp
- src/tnetdbg.cpp
- src/tnetdbg.hpp
- src/trivialserialize.cpp
- src/trivialserialize.hpp
- src/utils/misc.hpp
- src/utils/unused.hpp
int_to_enum takes always int; assert overflowing. UT
> J468 copy safe v2

- .travis.yml
- Make travis build fails if unit_tests are broken
- coveralls fix
> Travis CI - update

- do
- import fail function
- checking unbound variable and fix already unbound
Tested on cygwin 32-bit, cygwin 64-bit and ubuntu
> Update do script - cygwin 32-bit and 64-bit

- CMakeLists.txt
- fix windows installer gitian build
> [gitian] remove boost thread from BOOST_LIBS_LIST for MINGW build

- contrib/gitian-descriptors/main-build/galaxy-windows-script-master
> [gitian] windows fix bug with not provided boost libraries

- do
Usage of two threads as default in "do" script causes more and more frequent fails in our CI tests (travis and jenkins), the reason is probably a small amount of memory in these build systems during "make". Examples of fails:
- internal compiler error
- not recognizing preprocessor directives
After changes "make" will use only one thread. To have more threads during "make", use an environment variable THREADS, example:
THREADS=2 COVERAGE=1 EXTLEVEL=0  ./do --go"
> Handling THREADS envirnoment variable for "do" script

- src-tools/netmodel/netmodel.cpp
- src/asiotest.cpp
- src/project.hpp
- src/test/utils_wrap_thread.cpp
> metmodel - first version

- CMakeLists.txt
> [fix] make run works again when done in build/ too

- src/rpc/rpc.cpp
- src/rpc/rpc.hpp
> m_rpc_functions_map is protected by mutex

- src-tools/netmodel/netmodel.cpp
> [fix] MSVC [netmodel] add cfg_size_tuntap_maxread into lambda capture list

- CMakeLists.txt
- src/crypto/multikeys.cpp
- src/test/utils_wrap_thread.cpp
- build (make run !!) in maing dir
- git clear -xdf
- build (make run !!) in build/ dir (create it)
- git clear -xdf
- build with ./do , then cd build/  then make run
UT tests pass?
no warnings?
> Fix make run in build/ (rundevel.sh) warnings only re moving thread in UT

- src-gui/addressbookform.cpp
- src-gui/addressbookform.h
- src-gui/addressbookform.ui
- src-gui/addressmodel.cpp
- src-gui/addressmodel.h
- src-gui/main.cpp
- src-gui/mainwindow.cpp
- src-gui/mainwindow.ui
- src-gui/meshpeer.cpp
- src-gui/meshpeer.h
- src-gui/peereditdialog.ui
- src-gui/peerlistform.h
- src-gui/peerlistform.ui
- src-gui/peersmodel.cpp
- src-gui/peersmodel.h
- src-gui/quickstartdialog.cpp
- src-gui/quickstartdialog.ui
- src-gui/simpleGui.pro
- src-gui/statusform.cpp
- src-gui/tuntaprunner.cpp
- src-gui/tuntaprunner.h
- src/c_event_manager.hpp
- src/c_tun_device.hpp
- src/tuntap/freebsd/c_tuntap_freebsd_obj.cpp
- src/tuntap/freebsd/c_tuntap_freebsd_obj.hpp
less information while rpc log-in, limitation
> GUI improvments + GUI tuntap runner started + BSD work started (but not compiling on BSD yet)

- src/rpc/rpc.cpp
- src/rpc/rpc.hpp
- src/the_program_tunserver.cpp
- src/tunserver.cpp
now we can set rpc listen address
> create --rpc-listen-address option

- Jenkinsfile
add mac and gui build to jenkins
> add jenkins builds

- src-tools/netutils/test-perf/a.cpp
- src-tools/netutils/test-perf/go.sh
Merging older code, before prunning some old branches
> Merge older performance 1
